using System;
using System.Collections.Generic;

namespace OSE_Treasure.Items.MagicItems
{
    public sealed class Misc
    {
        public static string Roll()
        {
            var roll = RandomUtils.RollDice(RollType.d400);
            var idx = MiscTable.FindIndex(x => x.Item1 >= roll);
            return $"{MiscTable[idx].Item2}\n";
        }

        private static readonly List<Tuple<int, string>> MiscTable = new List<Tuple<int, string>>
        { 
            new Tuple<int, string>(2, "Alchemist's Beaker"),
            new Tuple<int, string>(3, "Amulet of Protection Against Possession"),
            new Tuple<int, string>(6, "Amulet of Protection Against Scrying"),
            new Tuple<int, string>(8, "Apparatus of the Crab"),
            new Tuple<int, string>(11, "Arrow of Location"),
            new Tuple<int, string>(12, "Bag of Devouring"),
            new Tuple<int, string>(17, "Bag of Holding"),
            new Tuple<int, string>(18, "Bag of Transformation"),
            new Tuple<int, string>(19, "Book of Foul Corruption"),
            new Tuple<int, string>(20, "Book of Infinite Spells"),
            new Tuple<int, string>(21, "Book of Sublime Holiness"),
            new Tuple<int, string>(22, "Boots of Dancing"),
            new Tuple<int, string>(27, "Boots of Levitation"),
            new Tuple<int, string>(31, "Boots of Speed"),
            new Tuple<int, string>(35, "Boots of Travelling and Leaping"),
            new Tuple<int, string>(50, "Bracers of Armour"),
            new Tuple<int, string>(52, "Bracers of Defencelessness"),
            new Tuple<int, string>(59, "Brooch of Shielding"),
            new Tuple<int, string>(64, "Broom of Flying"),
            new Tuple<int, string>(70, "Candle of Invocation"),
            new Tuple<int, string>(72, "Chime of Opening"),
            new Tuple<int, string>(73, "Chime of Ravening"),
            new Tuple<int, string>(85, "Cloak of Defense"),
            new Tuple<int, string>(95, "Cloak of Flight"),
            new Tuple<int, string>(97, "Cloak of Poison"),
            new Tuple<int, string>(100, "Cloak of the Manta Ray"),

            new Tuple<int, string>(105, "Crystal Ball"),
            new Tuple<int, string>(107, "Crystal Ball with Clairaudience"),
            new Tuple<int, string>(108, "Crystal Ball with ESP"),
            new Tuple<int, string>(109, "Crystal Hypnosis Ball"),
            new Tuple<int, string>(111, "Cube of Force"),
            new Tuple<int, string>(113, "Cube of Frost Resistance"),
            new Tuple<int, string>(116, "Decanter of Endless Water"),
            new Tuple<int, string>(120, "Deck of Many Things"),
            new Tuple<int, string>(124, "Displacer Cloak"),
            new Tuple<int, string>(126, "Drums of Panic"),
            new Tuple<int, string>(127, "Drums of Thunder"),
            new Tuple<int, string>(133, "Dust of Appearance"),
            new Tuple<int, string>(139, "Dust of Disappearance"),
            new Tuple<int, string>(140, "Dust of Sneezing and Choking"),
            new Tuple<int, string>(141, "Efreeti Bottle"),
            new Tuple<int, string>(143, "Elemental Summoning Device: Air"),
            new Tuple<int, string>(145, "Elemental Summoning Device: Earth"),
            new Tuple<int, string>(147, "Elemental Summoning Device: Fire"),
            new Tuple<int, string>(149, "Elemental Summoning Device: Water"),
            new Tuple<int, string>(159, "Elven Cloak and Boots"),
            new Tuple<int, string>(160, "Eyes of Charming"),
            new Tuple<int, string>(162, "Eyes of Minuscule Sight"),
            new Tuple<int, string>(163, "Eyes of Petrification"),
            new Tuple<int, string>(165, "Eyes of the Eagle"),
            new Tuple<int, string>(180, "Feather Token"),
            new Tuple<int, string>(195, "Figurine of Wondrous Power"),
            new Tuple<int, string>(197, "Flying Carpet"),
            new Tuple<int, string>(198, "Folding Boat"),
            new Tuple<int, string>(200, "Gauntlets of Ogre Power"),

            new Tuple<int, string>(201, "Gem of Brightness"),
            new Tuple<int, string>(202, "Gem of Monster Attraction"),
            new Tuple<int, string>(203, "Gem of Pristine Faceting"),
            new Tuple<int, string>(204, "Gem of Seeing"),
            new Tuple<int, string>(205, "Girdle of Giant Strength"),
            new Tuple<int, string>(207, "Gloves of Dexterity"),
            new Tuple<int, string>(210, "Gloves of Swimming and Climbing"),
            new Tuple<int, string>(212, "Helm of Alignment Changing"),
            new Tuple<int, string>(217, "Helm of Read Languages and Magic"),
            new Tuple<int, string>(219, "Helm of Telepathy"),
            new Tuple<int, string>(220, "Helm of Teleportation"),
            new Tuple<int, string>(221, "Horn of Blasting"),
            new Tuple<int, string>(222, "Horn of Cave-Ins"),
            new Tuple<int, string>(224, "Horn of Frothing"),
            new Tuple<int, string>(228, "Horn of the Tritons"),
            new Tuple<int, string>(235, "Horn of Valhalla"),
            new Tuple<int, string>(237, "Horseshoes of a Zephyr"),
            new Tuple<int, string>(240, "Horseshoes of Speed"),
            new Tuple<int, string>(245, "Incense of Meditation"),
            new Tuple<int, string>(246, "Incense of Obsession"),
            new Tuple<int, string>(248, "Instant Fortress"),
            new Tuple<int, string>(249, "Ioun Stones"),
            new Tuple<int, string>(251, "Iron Flask"),
            new Tuple<int, string>(253, "Jug of Endless Liquids"),
            new Tuple<int, string>(254, "Libram of Arcane Power"),
            new Tuple<int, string>(256, "Loadstone"),
            new Tuple<int, string>(258, "Luckstone"),
            new Tuple<int, string>(259, "Lyre of Building"),
            new Tuple<int, string>(261, "Marvellous Pigments"),
            new Tuple<int, string>(264, "Medallion of ESP 30'"),
            new Tuple<int, string>(266, "Medallion of ESP 90'"),
            new Tuple<int, string>(268, "Medallion of Thought Projection"),
            new Tuple<int, string>(269, "Mirror of Life Trapping"),
            new Tuple<int, string>(270, "Mirror of Mental Prowess"),
            new Tuple<int, string>(271, "Mirror of Opposition"),
            new Tuple<int, string>(274, "Necklace of Adaptation"),
            new Tuple<int, string>(278, "Necklace of Fireballs"),
            new Tuple<int, string>(280, "Necklace of Strangulation"),
            new Tuple<int, string>(284, "Net of Aquatic Snaring"),
            new Tuple<int, string>(287, "Net of Snaring"),
            new Tuple<int, string>(290, "Oil of Insubstantiality"),
            new Tuple<int, string>(293, "Oil of Slipperiness"),
            new Tuple<int, string>(295, "Pearl of Power"),
            new Tuple<int, string>(297, "Pearl of Wisdom"),
            new Tuple<int, string>(300, "Periapt of Foul Rotting"),

            new Tuple<int, string>(302, "Periapt of Health"),
            new Tuple<int, string>(309, "Periapt of Proof Against Poison"),
            new Tuple<int, string>(313, "Periapt of Wound Closure"),
            new Tuple<int, string>(315, "Phylactery of Betrayal"),
            new Tuple<int, string>(321, "Phylactery of Faithfulness"),
            new Tuple<int, string>(325, "Phylactery of Longevity"),
            new Tuple<int, string>(333, "Pipes of the Sewers"),
            new Tuple<int, string>(334, "Portable Hole"),
            new Tuple<int, string>(336, "Purse of the Plentiful Coin"),
            new Tuple<int, string>(344, "Restorative Ointment"),
            new Tuple<int, string>(351, "Robe of Bending"),
            new Tuple<int, string>(352, "Robe of Eyes"),
            new Tuple<int, string>(353, "Robe of Powerlessness"),
            new Tuple<int, string>(354, "Robe of Scintillating Colours"),
            new Tuple<int, string>(355, "Robe of the Archmagi"),
            new Tuple<int, string>(363, "Robe of Useful Items"),
            new Tuple<int, string>(369, "Rope of Climbing"),
            new Tuple<int, string>(373, "Rope of Entanglement"),
            new Tuple<int, string>(375, "Rope of Strangulation"),
            new Tuple<int, string>(376, "Rug of Suffocation"),
            new Tuple<int, string>(377, "Saw of Felling"),
            new Tuple<int, string>(379, "Scarab of Chaos"),
            new Tuple<int, string>(380, "Scarab of Death"),
            new Tuple<int, string>(386, "Scarab of Protection"),
            new Tuple<int, string>(389, "Scarab of Rage"),
            new Tuple<int, string>(390, "Spade of Mighty Digging"),
            new Tuple<int, string>(391, "Sphere of Annihilation"),
            new Tuple<int, string>(394, "Sweet Water"),
            new Tuple<int, string>(395, "Talisman of the Sphere"),
            new Tuple<int, string>(397, "Vacuous Grimoire"),
            new Tuple<int, string>(400, "Well of Many Worlds")
        };
    }
}